server:
  port: 9001
spring:
  application:
    name: rabbitmq-consumer
  boot:
    admin:
      client:
        url: http://localhost:8000
  cloud:
    consul:
      discovery:
        register: true
        service-name: rabbitmq-consumer
      host: localhost
      port: 8500
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
