eureka:
  client:
    register-with-eureka: true
spring:
  application:
    name: image-service
  cloud:
    config:
      uri: http://localhost:8888
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 8081