server:
  port: 8081
spring:
  application:
    name: AMS
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
logging:
  level:
    org.hibernate.stat: debug
    org.hibernate.type: trace
   